### ISSUE TITLE
[PE-D][Tester E] There is no current feature to tag a contact to an event

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-4/tp#142]
I would presume that this application will serve as a scheduler and also an addressbook. There is an informal way to link a contact to a event by typing their name, but no concrete relation. **There may be more efficient scheduling applications out there, as the inputting of date is quite troublesome and prone to typos.** 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: starsia/ped#13

**Comment by Rishit02** [comment]
This is just a way to look at appointments, and is not a reminder application.
