### ISSUE TITLE
[PE-D][Tester B] UG discription for schedule delete command does not mention case sensitivity

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-4/tp#145]
**Expected**
Schedule delete command is case sensitive, so UG should state as such
**Actual**
There is no mention of case sensitivity in the description for schedule delete command:

![image.png](https://raw.githubusercontent.com/ReflectiveObsidian/ped/main/files/7a2d1d8c-1bef-4d41-a851-76bde2b4bfa3.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ReflectiveObsidian/ped#7

**Comment by Rishit02** [comment]
We have updated the UG to reflect this.
