### ISSUE TITLE
[PE-D][Tester D] Emails not allowed to be added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-4/tp#152]
Email not allowed although it satisfies email requirement of being alphanumeric and having special characters stated in the bug.

![Screenshot 2024-04-05 at 5.00.17 PM.png](https://raw.githubusercontent.com/Xilef121/ped/main/files/75fa6d16-d989-4d15-b10b-f8966930d0b1.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Xilef121/ped#4

**Comment by Rishit02** [comment]
According to the internet, that is an invalid email as there are 2 consecutive periods, and cannot even exist. Thus, we would like to reject this bug.
