### ISSUE TITLE
[PE-D][Tester E] Documentation: x and arrow up don’t work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-4/tp#154]
Not sure what these are

![image.png](https://raw.githubusercontent.com/starsia/ped/main/files/5e199de6-d391-495b-b804-f25c67140e46.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: starsia/ped#16

**Comment by pjanthony2001** [comment]
Rejected: These objects rendered in the PDF format are not supposed to be clickable
