### ISSUE TITLE
[PE-D][Tester E] Foreign characters in names are not allowed in add command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-4/tp#166]
I am using the add command. `add n/小明 p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 k/Joe Doe d/Has a history of memory loss t/mentalIllness t/owesMoney`

![image.png](https://raw.githubusercontent.com/starsia/ped/main/files/8cc4c157-c16a-4c28-b96c-e87dd6846df4.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: starsia/ped#20

**Comment by Rishit02** [comment]
Planned enhancement
