### ISSUE TITLE
[PE-D][Tester B] Add command allows multiple users with the same name to be added, if they have different cases

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-4/tp#167]
Steps to reproduce:
1. Launch app with no contacts
2. Add users with following 2 commands:

add n/John Doe p/98765432 e/johnd@example.com a/John street, Block 123, #01-01 d/Suffers from depression k/Jasmin Doe t/mentalIllness

add n/John doe p/98765432 e/johnd@example.com a/John street, Block 123, #01-01 d/Suffers from depression k/Jasmin Doe t/mentalIllness

Expected:
Duplicate name should be detected and rejected, so that the update function (which relies on name) works properly.

Actual: Both john doe are added to the contacts list, thus they cannot be updated, only deleted.

Screenshot:

![image.png](https://raw.githubusercontent.com/ReflectiveObsidian/ped/main/files/5c891964-89d1-4794-944b-a889c09473b0.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ReflectiveObsidian/ped#12

**Comment by Rishit02** [comment]
Fixed
