### ISSUE TITLE
[PE-D][Tester D] schedule delete is affected by extra white spaces

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-4/tp#184]
"schedule delete h/ House  Visit" will not be allowed as House  Visit is not recognised to be the same as House Visit.

![Screenshot 2024-04-05 at 6.09.06 PM.png](https://raw.githubusercontent.com/Xilef121/ped/main/files/03f9155d-ce8b-4dad-8fa7-992785b04b42.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Xilef121/ped#11

**Comment by Rishit02** [comment]
Unable to reproduce error. Unsure where exactly the extra whitespace is added.
